const players = [
    {
        "serial": "01",
        "player_name": "Bruno Fernandes",
        "club": "Man. United",
        "position": "Midfielder",
        "assists": 7,
        "corner_taken": 10,
        "offsides": 2,
        "dribbles": 7,
        "match_played": 7
    },
    {
        "serial": "02",
        "player_name": "Vinícius Júnior",
        "club": "Real Madrid",
        "position": "Forward",
        "assists": 6,
        "corner_taken": 3,
        "offsides": 4,
        "dribbles": 83,
        "match_played": 13
    },
    {
        "serial": "02",
        "player_name": "Sané",
        "club": "Bayern",
        "position": "Midfielder",
        "assists": 6,
        "corner_taken": 3,
        "offsides": 3,
        "dribbles": 32,
        "match_played": 10
    },
    {
        "serial": "04",
        "player_name": "Antony",
        "club": "Ajax",
        "position": "Forward",
        "assists": 5,
        "corner_taken": 3,
        "offsides": 4,
        "dribbles": 28,
        "match_played": 7
    },
    {
        "serial": "05",
        "player_name": "Alexander-Arnold",
        "club": "Liverpool",
        "position": "Defender",
        "assists": 4,
        "corner_taken": 36,
        "offsides": 0,
        "dribbles": 9,
        "match_played": 9
    },
    {
        "serial": "05",
        "player_name": "De Bruyne",
        "club": "Man. City",
        "position": "Midfielder",
        "assists": 4,
        "corner_taken": 18,
        "offsides": 0,
        "dribbles": 14,
        "match_played": 10
    },
    {
        "serial": "05",
        "player_name": "Modrić",
        "club": "Real Madrid",
        "position": "Midfielder",
        "assists": 4,
        "corner_taken": 10,
        "offsides": 0,
        "dribbles": 8,
        "match_played": 13
    },
    {
        "serial": "05",
        "player_name": "João Mário",
        "club": "Benfica",
        "position": "Midfielder",
        "assists": 4,
        "corner_taken": 8,
        "offsides": 0,
        "dribbles": 7,
        "match_played": 8
    },
    {
        "serial": "05",
        "player_name": "Mbappé",
        "club": "Paris",
        "position": "Forward",
        "assists": 4,
        "corner_taken": 4,
        "offsides": 8,
        "dribbles": 43,
        "match_played": 8
    },
    {
        "serial": "05",
        "player_name": "Gerard Moreno",
        "club": "Villarreal",
        "position": "Forward",
        "assists": 4,
        "corner_taken": 0,
        "offsides": 3,
        "dribbles": 9,
        "match_played": 7
    },
    {
        "serial": "05",
        "player_name": "Capoue",
        "club": "Villarreal",
        "position": "Midfielder",
        "assists": 4,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 17,
        "match_played": 12
    },
    {
        "serial": 12,
        "player_name": "Parejo",
        "club": "Villarreal",
        "position": "Midfielder",
        "assists": 3,
        "corner_taken": 36,
        "offsides": 0,
        "dribbles": 4,
        "match_played": 12
    },
    {
        "serial": 12,
        "player_name": "Grimaldo",
        "club": "Benfica",
        "position": "Defender",
        "assists": 3,
        "corner_taken": 11,
        "offsides": 1,
        "dribbles": 10,
        "match_played": 10
    },
    {
        "serial": 12,
        "player_name": "Müller",
        "club": "Bayern",
        "position": "Forward",
        "assists": 3,
        "corner_taken": 10,
        "offsides": 8,
        "dribbles": 2,
        "match_played": 10
    },
    {
        "serial": 12,
        "player_name": "Arnold",
        "club": "Wolfsburg",
        "position": "Midfielder",
        "assists": 3,
        "corner_taken": 10,
        "offsides": 0,
        "dribbles": 1,
        "match_played": 6
    },
    {
        "serial": 12,
        "player_name": "Angeliño",
        "club": "Leipzig",
        "position": "Defender",
        "assists": 3,
        "corner_taken": 8,
        "offsides": 0,
        "dribbles": 4,
        "match_played": 5
    },
    {
        "serial": 12,
        "player_name": "Coman",
        "club": "Bayern",
        "position": "Forward",
        "assists": 3,
        "corner_taken": 4,
        "offsides": 4,
        "dribbles": 59,
        "match_played": 9
    },
    {
        "serial": 12,
        "player_name": "Bernardo Silva",
        "club": "Man. City",
        "position": "Midfielder",
        "assists": 3,
        "corner_taken": 2,
        "offsides": 3,
        "dribbles": 18,
        "match_played": 11
    },
    {
        "serial": 12,
        "player_name": "Bellingham",
        "club": "Dortmund",
        "position": "Midfielder",
        "assists": 3,
        "corner_taken": 1,
        "offsides": 1,
        "dribbles": 24,
        "match_played": 6
    },
    {
        "serial": 12,
        "player_name": "Zapata",
        "club": "Atalanta",
        "position": "Forward",
        "assists": 3,
        "corner_taken": 0,
        "offsides": 7,
        "dribbles": 10,
        "match_played": 6
    },
    {
        "serial": 12,
        "player_name": "Lewandowski",
        "club": "Bayern",
        "position": "Forward",
        "assists": 3,
        "corner_taken": 0,
        "offsides": 7,
        "dribbles": 1,
        "match_played": 10
    },
    {
        "serial": 12,
        "player_name": "João Cancelo",
        "club": "Man. City",
        "position": "Defender",
        "assists": 3,
        "corner_taken": 0,
        "offsides": 2,
        "dribbles": 26,
        "match_played": 9
    },
    {
        "serial": 12,
        "player_name": "Cristiano",
        "club": "Sheriff",
        "position": "Defender",
        "assists": 3,
        "corner_taken": 0,
        "offsides": 1,
        "dribbles": 7,
        "match_played": 6
    },
    {
        "serial": 24,
        "player_name": "Mahrez",
        "club": "Man. City",
        "position": "Midfielder",
        "assists": 2,
        "corner_taken": 30,
        "offsides": 5,
        "dribbles": 28,
        "match_played": 12
    },
    {
        "serial": 24,
        "player_name": "Robertson",
        "club": "Liverpool",
        "position": "Defender",
        "assists": 2,
        "corner_taken": 27,
        "offsides": 1,
        "dribbles": 9,
        "match_played": 10
    },
    {
        "serial": 24,
        "player_name": "Ziyech",
        "club": "Chelsea",
        "position": "Midfielder",
        "assists": 2,
        "corner_taken": 23,
        "offsides": 0,
        "dribbles": 12,
        "match_played": 9
    },
    {
        "serial": 24,
        "player_name": "Gündoğan",
        "club": "Man. City",
        "position": "Midfielder",
        "assists": 2,
        "corner_taken": 16,
        "offsides": 1,
        "dribbles": 3,
        "match_played": 10
    },
    {
        "serial": 24,
        "player_name": "Tsimikas",
        "club": "Liverpool",
        "position": "Defender",
        "assists": 2,
        "corner_taken": 16,
        "offsides": 0,
        "dribbles": 4,
        "match_played": 5
    },
    {
        "serial": 24,
        "player_name": "Foden",
        "club": "Man. City",
        "position": "Midfielder",
        "assists": 2,
        "corner_taken": 13,
        "offsides": 6,
        "dribbles": 12,
        "match_played": 11
    },
    {
        "serial": 24,
        "player_name": "Pjanic",
        "club": "Beşiktaş",
        "position": "Midfielder",
        "assists": 2,
        "corner_taken": 9,
        "offsides": 0,
        "dribbles": 4,
        "match_played": 3
    },
    {
        "serial": 24,
        "player_name": "Forsberg",
        "club": "Leipzig",
        "position": "Forward",
        "assists": 2,
        "corner_taken": 9,
        "offsides": 0,
        "dribbles": 3,
        "match_played": 6
    },
    {
        "serial": 24,
        "player_name": "Bernardeschi",
        "club": "Juventus",
        "position": "Midfielder",
        "assists": 2,
        "corner_taken": 7,
        "offsides": 1,
        "dribbles": 7,
        "match_played": 5
    },
    {
        "serial": 24,
        "player_name": "Dahoud",
        "club": "Dortmund",
        "position": "Midfielder",
        "assists": 2,
        "corner_taken": 7,
        "offsides": 1,
        "dribbles": 3,
        "match_played": 4
    },
    {
        "serial": 24,
        "player_name": "Pedro Gonçalves",
        "club": "Sporting CP",
        "position": "Midfielder",
        "assists": 2,
        "corner_taken": 7,
        "offsides": 0,
        "dribbles": 10,
        "match_played": 5
    },
    {
        "serial": 24,
        "player_name": "Mount",
        "club": "Chelsea",
        "position": "Midfielder",
        "assists": 2,
        "corner_taken": 7,
        "offsides": 0,
        "dribbles": 6,
        "match_played": 7
    },
    {
        "serial": 24,
        "player_name": "Douglas Santos",
        "club": "Zenit",
        "position": "Defender",
        "assists": 2,
        "corner_taken": 6,
        "offsides": 1,
        "dribbles": 3,
        "match_played": 5
    },
    {
        "serial": 24,
        "player_name": "Rakitskyy",
        "club": "Zenit",
        "position": "Defender",
        "assists": 2,
        "corner_taken": 6,
        "offsides": 0,
        "dribbles": 4,
        "match_played": 6
    },
    {
        "serial": 24,
        "player_name": "Tadić",
        "club": "Ajax",
        "position": "Forward",
        "assists": 2,
        "corner_taken": 5,
        "offsides": 5,
        "dribbles": 13,
        "match_played": 7
    },
    {
        "serial": 24,
        "player_name": "Asensio",
        "club": "Real Madrid",
        "position": "Forward",
        "assists": 2,
        "corner_taken": 5,
        "offsides": 0,
        "dribbles": 1,
        "match_played": 8
    },
    {
        "serial": 24,
        "player_name": "Aaronson",
        "club": "Salzburg",
        "position": "Midfielder",
        "assists": 2,
        "corner_taken": 4,
        "offsides": 5,
        "dribbles": 9,
        "match_played": 8
    },
    {
        "serial": 24,
        "player_name": "Danjuma",
        "club": "Villarreal",
        "position": "Midfielder",
        "assists": 2,
        "corner_taken": 3,
        "offsides": 8,
        "dribbles": 31,
        "match_played": 11
    },
    {
        "serial": 24,
        "player_name": "Shaw",
        "club": "Man. United",
        "position": "Defender",
        "assists": 2,
        "corner_taken": 3,
        "offsides": 1,
        "dribbles": 1,
        "match_played": 5
    },
    {
        "serial": 24,
        "player_name": "Gnabry",
        "club": "Bayern",
        "position": "Forward",
        "assists": 2,
        "corner_taken": 3,
        "offsides": 0,
        "dribbles": 12,
        "match_played": 8
    },
    {
        "serial": 24,
        "player_name": "Griezmann",
        "club": "Atlético",
        "position": "Forward",
        "assists": 2,
        "corner_taken": 2,
        "offsides": 1,
        "dribbles": 8,
        "match_played": 9
    },
    {
        "serial": 24,
        "player_name": "Renan Lodi",
        "club": "Atlético",
        "position": "Defender",
        "assists": 2,
        "corner_taken": 1,
        "offsides": 5,
        "dribbles": 9,
        "match_played": 10
    },
    {
        "serial": 24,
        "player_name": "Rodrygo",
        "club": "Real Madrid",
        "position": "Forward",
        "assists": 2,
        "corner_taken": 1,
        "offsides": 1,
        "dribbles": 20,
        "match_played": 11
    },
    {
        "serial": 24,
        "player_name": "Hudson-Odoi",
        "club": "Chelsea",
        "position": "Midfielder",
        "assists": 2,
        "corner_taken": 1,
        "offsides": 1,
        "dribbles": 15,
        "match_played": 5
    },
    {
        "serial": 24,
        "player_name": "Jorginho",
        "club": "Chelsea",
        "position": "Midfielder",
        "assists": 2,
        "corner_taken": 1,
        "offsides": 0,
        "dribbles": 1,
        "match_played": 8
    },
    {
        "serial": 24,
        "player_name": "André Silva",
        "club": "Leipzig",
        "position": "Forward",
        "assists": 2,
        "corner_taken": 0,
        "offsides": 9,
        "dribbles": 5,
        "match_played": 6
    },
    {
        "serial": 24,
        "player_name": "Sterling",
        "club": "Man. City",
        "position": "Forward",
        "assists": 2,
        "corner_taken": 0,
        "offsides": 6,
        "dribbles": 14,
        "match_played": 12
    },
    {
        "serial": 24,
        "player_name": "Salah",
        "club": "Liverpool",
        "position": "Forward",
        "assists": 2,
        "corner_taken": 0,
        "offsides": 5,
        "dribbles": 49,
        "match_played": 13
    },
    {
        "serial": 24,
        "player_name": "Ikoné",
        "club": "LOSC",
        "position": "Midfielder",
        "assists": 2,
        "corner_taken": 0,
        "offsides": 1,
        "dribbles": 15,
        "match_played": 5
    },
    {
        "serial": 24,
        "player_name": "Werner",
        "club": "Chelsea",
        "position": "Forward",
        "assists": 2,
        "corner_taken": 0,
        "offsides": 1,
        "dribbles": 10,
        "match_played": 5
    },
    {
        "serial": 24,
        "player_name": "Jones",
        "club": "Liverpool",
        "position": "Midfielder",
        "assists": 2,
        "corner_taken": 0,
        "offsides": 1,
        "dribbles": 0,
        "match_played": 4
    },
    {
        "serial": 24,
        "player_name": "Matheus Nunes",
        "club": "Sporting CP",
        "position": "Midfielder",
        "assists": 2,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 21,
        "match_played": 6
    },
    {
        "serial": 24,
        "player_name": "Davies",
        "club": "Bayern",
        "position": "Midfielder",
        "assists": 2,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 18,
        "match_played": 7
    },
    {
        "serial": 24,
        "player_name": "Mazraoui",
        "club": "Ajax",
        "position": "Defender",
        "assists": 2,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 13,
        "match_played": 8
    },
    {
        "serial": 24,
        "player_name": "Mendy",
        "club": "Real Madrid",
        "position": "Defender",
        "assists": 2,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 8,
        "match_played": 10
    },
    {
        "serial": 24,
        "player_name": "Keïta",
        "club": "Liverpool",
        "position": "Midfielder",
        "assists": 2,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 6,
        "match_played": 10
    },
    {
        "serial": 24,
        "player_name": "Henderson",
        "club": "Liverpool",
        "position": "Midfielder",
        "assists": 2,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 2,
        "match_played": 12
    },
    {
        "serial": 24,
        "player_name": "Vidal",
        "club": "Inter",
        "position": "Midfielder",
        "assists": 2,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 2,
        "match_played": 7
    },
    {
        "serial": 24,
        "player_name": "Ricardo Esgaio",
        "club": "Sporting CP",
        "position": "Defender",
        "assists": 2,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 1,
        "match_played": 8
    },
    {
        "serial": 24,
        "player_name": "Fernandinho",
        "club": "Man. City",
        "position": "Midfielder",
        "assists": 2,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 1,
        "match_played": 8
    },
    {
        "serial": 64,
        "player_name": "Seiwald",
        "club": "Salzburg",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 18,
        "offsides": 1,
        "dribbles": 5,
        "match_played": 8
    },
    {
        "serial": 64,
        "player_name": "Berghuis",
        "club": "Ajax",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 15,
        "offsides": 2,
        "dribbles": 3,
        "match_played": 8
    },
    {
        "serial": 64,
        "player_name": "Gravenberch",
        "club": "Ajax",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 15,
        "offsides": 1,
        "dribbles": 18,
        "match_played": 8
    },
    {
        "serial": 64,
        "player_name": "Lang",
        "club": "Club Brugge",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 12,
        "offsides": 5,
        "dribbles": 17,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Aebischer",
        "club": "Young Boys",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 11,
        "offsides": 0,
        "dribbles": 6,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Tsygankov",
        "club": "Dynamo Kyiv",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 10,
        "offsides": 0,
        "dribbles": 8,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Oxlade-Chamberlain",
        "club": "Liverpool",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 9,
        "offsides": 0,
        "dribbles": 6,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "S. Thill",
        "club": "Sheriff",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 9,
        "offsides": 0,
        "dribbles": 1,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Di María",
        "club": "Paris",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 8,
        "offsides": 1,
        "dribbles": 3,
        "match_played": 5
    },
    {
        "serial": 64,
        "player_name": "Koopmeiners",
        "club": "Atalanta",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 8,
        "offsides": 0,
        "dribbles": 1,
        "match_played": 5
    },
    {
        "serial": 64,
        "player_name": "Neymar",
        "club": "Paris",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 7,
        "offsides": 1,
        "dribbles": 27,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Lemar",
        "club": "Atlético",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 7,
        "offsides": 0,
        "dribbles": 7,
        "match_played": 8
    },
    {
        "serial": 64,
        "player_name": "Rakitić",
        "club": "Sevilla",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 7,
        "offsides": 0,
        "dribbles": 0,
        "match_played": 5
    },
    {
        "serial": 64,
        "player_name": "De Ketelaere",
        "club": "Club Brugge",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 6,
        "offsides": 10,
        "dribbles": 6,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Malcom",
        "club": "Zenit",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 6,
        "offsides": 2,
        "dribbles": 12,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Vormer",
        "club": "Club Brugge",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 6,
        "offsides": 1,
        "dribbles": 0,
        "match_played": 4
    },
    {
        "serial": 64,
        "player_name": "Rieder",
        "club": "Young Boys",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 6,
        "offsides": 0,
        "dribbles": 2,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Reus",
        "club": "Dortmund",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 5,
        "offsides": 7,
        "dribbles": 5,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Alan Patrick",
        "club": "Shakhtar Donetsk",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 4,
        "offsides": 0,
        "dribbles": 5,
        "match_played": 4
    },
    {
        "serial": 64,
        "player_name": "Koke",
        "club": "Atlético",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 4,
        "offsides": 0,
        "dribbles": 2,
        "match_played": 9
    },
    {
        "serial": 64,
        "player_name": "Milner",
        "club": "Liverpool",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 4,
        "offsides": 0,
        "dribbles": 1,
        "match_played": 8
    },
    {
        "serial": 64,
        "player_name": "Grealish",
        "club": "Man. City",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 3,
        "offsides": 6,
        "dribbles": 18,
        "match_played": 7
    },
    {
        "serial": 64,
        "player_name": "T. Hernández",
        "club": "Milan",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 3,
        "offsides": 4,
        "dribbles": 10,
        "match_played": 5
    },
    {
        "serial": 64,
        "player_name": "Benzema",
        "club": "Real Madrid",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 2,
        "offsides": 9,
        "dribbles": 18,
        "match_played": 12
    },
    {
        "serial": 64,
        "player_name": "Iličić",
        "club": "Atalanta",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 2,
        "offsides": 2,
        "dribbles": 13,
        "match_played": 4
    },
    {
        "serial": 64,
        "player_name": "Dybala",
        "club": "Juventus",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 2,
        "offsides": 0,
        "dribbles": 8,
        "match_played": 5
    },
    {
        "serial": 64,
        "player_name": "Vanaken",
        "club": "Club Brugge",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 2,
        "offsides": 0,
        "dribbles": 7,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Bruno Tabata",
        "club": "Sporting CP",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 2,
        "offsides": 0,
        "dribbles": 2,
        "match_played": 4
    },
    {
        "serial": 64,
        "player_name": "João Félix",
        "club": "Atlético",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 1,
        "offsides": 3,
        "dribbles": 21,
        "match_played": 8
    },
    {
        "serial": 64,
        "player_name": "Taremi",
        "club": "Porto",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 1,
        "offsides": 2,
        "dribbles": 4,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Ocampos",
        "club": "Sevilla",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 1,
        "offsides": 1,
        "dribbles": 16,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Moumi Ngamaleu",
        "club": "Young Boys",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 1,
        "offsides": 0,
        "dribbles": 34,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Zinchenko",
        "club": "Man. City",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 1,
        "offsides": 0,
        "dribbles": 3,
        "match_played": 8
    },
    {
        "serial": 64,
        "player_name": "Aurier",
        "club": "Villarreal",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 1,
        "offsides": 0,
        "dribbles": 0,
        "match_played": 5
    },
    {
        "serial": 64,
        "player_name": "Mané",
        "club": "Liverpool",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 9,
        "dribbles": 17,
        "match_played": 13
    },
    {
        "serial": 64,
        "player_name": "Paulinho",
        "club": "Sporting CP",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 5,
        "dribbles": 8,
        "match_played": 8
    },
    {
        "serial": 64,
        "player_name": "Diogo Jota",
        "club": "Liverpool",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 4,
        "dribbles": 19,
        "match_played": 11
    },
    {
        "serial": 64,
        "player_name": "Jesus",
        "club": "Man. City",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 4,
        "dribbles": 7,
        "match_played": 8
    },
    {
        "serial": 64,
        "player_name": "Rafa Silva",
        "club": "Benfica",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 3,
        "dribbles": 27,
        "match_played": 9
    },
    {
        "serial": 64,
        "player_name": "Rafael Leão",
        "club": "Milan",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 3,
        "dribbles": 16,
        "match_played": 4
    },
    {
        "serial": 64,
        "player_name": "Valverde",
        "club": "Real Madrid",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 3,
        "dribbles": 10,
        "match_played": 11
    },
    {
        "serial": 64,
        "player_name": "Haller",
        "club": "Ajax",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 3,
        "dribbles": 9,
        "match_played": 8
    },
    {
        "serial": 64,
        "player_name": "Greenwood",
        "club": "Man. United",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 3,
        "dribbles": 6,
        "match_played": 4
    },
    {
        "serial": 64,
        "player_name": "Alexis Sánchez",
        "club": "Inter",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 3,
        "dribbles": 2,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Luis Díaz",
        "club": "Liverpool",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 2,
        "dribbles": 42,
        "match_played": 13
    },
    {
        "serial": 64,
        "player_name": "Perišić",
        "club": "Inter",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 2,
        "dribbles": 13,
        "match_played": 8
    },
    {
        "serial": 64,
        "player_name": "Kristensen",
        "club": "Salzburg",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 2,
        "dribbles": 12,
        "match_played": 8
    },
    {
        "serial": 64,
        "player_name": "Džeko",
        "club": "Inter",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 2,
        "dribbles": 4,
        "match_played": 7
    },
    {
        "serial": 64,
        "player_name": "Dzyuba",
        "club": "Zenit",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 2,
        "dribbles": 1,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Pavard",
        "club": "Bayern",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 2,
        "dribbles": 0,
        "match_played": 10
    },
    {
        "serial": 64,
        "player_name": "Van Dijk",
        "club": "Liverpool",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 2,
        "dribbles": 0,
        "match_played": 9
    },
    {
        "serial": 64,
        "player_name": "Musiala",
        "club": "Bayern",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 1,
        "dribbles": 20,
        "match_played": 8
    },
    {
        "serial": 64,
        "player_name": "Traore",
        "club": "Sheriff",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 1,
        "dribbles": 13,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Pulišić",
        "club": "Chelsea",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 1,
        "dribbles": 11,
        "match_played": 7
    },
    {
        "serial": 64,
        "player_name": "Mæhle",
        "club": "Atalanta",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 1,
        "dribbles": 11,
        "match_played": 5
    },
    {
        "serial": 64,
        "player_name": "Carvajal",
        "club": "Real Madrid",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 1,
        "dribbles": 9,
        "match_played": 11
    },
    {
        "serial": 64,
        "player_name": "Blind",
        "club": "Ajax",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 1,
        "dribbles": 8,
        "match_played": 8
    },
    {
        "serial": 64,
        "player_name": "Meunier",
        "club": "Dortmund",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 1,
        "dribbles": 7,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Zeki Çelik",
        "club": "LOSC",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 1,
        "dribbles": 5,
        "match_played": 7
    },
    {
        "serial": 64,
        "player_name": "Gomes",
        "club": "LOSC",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 1,
        "dribbles": 3,
        "match_played": 4
    },
    {
        "serial": 64,
        "player_name": "Camavinga",
        "club": "Real Madrid",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 1,
        "dribbles": 2,
        "match_played": 10
    },
    {
        "serial": 64,
        "player_name": "Bentancur",
        "club": "Juventus",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 1,
        "dribbles": 2,
        "match_played": 5
    },
    {
        "serial": 64,
        "player_name": "Azmoun",
        "club": "Zenit",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 1,
        "dribbles": 2,
        "match_played": 5
    },
    {
        "serial": 64,
        "player_name": "Palomino",
        "club": "Atalanta",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 1,
        "dribbles": 0,
        "match_played": 5
    },
    {
        "serial": 64,
        "player_name": "Jordi Alba",
        "club": "Barcelona",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 1,
        "dribbles": 0,
        "match_played": 5
    },
    {
        "serial": 64,
        "player_name": "Adeyemi",
        "club": "Salzburg",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 23,
        "match_played": 8
    },
    {
        "serial": 64,
        "player_name": "Birmančević",
        "club": "Malmö",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 19,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Brahim Díaz",
        "club": "Milan",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 19,
        "match_played": 5
    },
    {
        "serial": 64,
        "player_name": "Loftus-Cheek",
        "club": "Chelsea",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 15,
        "match_played": 8
    },
    {
        "serial": 64,
        "player_name": "Zappacosta",
        "club": "Atalanta",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 12,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Pedraza",
        "club": "Villarreal",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 9,
        "match_played": 10
    },
    {
        "serial": 64,
        "player_name": "Lucas Vázquez",
        "club": "Real Madrid",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 6,
        "match_played": 8
    },
    {
        "serial": 64,
        "player_name": "Freuler",
        "club": "Atalanta",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 6,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Dumfries",
        "club": "Inter",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 5,
        "match_played": 7
    },
    {
        "serial": 64,
        "player_name": "Olmo",
        "club": "Leipzig",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 5,
        "match_played": 2
    },
    {
        "serial": 64,
        "player_name": "Gonçalo Ramos",
        "club": "Benfica",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 4,
        "match_played": 7
    },
    {
        "serial": 64,
        "player_name": "Kanté",
        "club": "Chelsea",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 4,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Laimer",
        "club": "Leipzig",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 4,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Moi Gómez",
        "club": "Villarreal",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 4,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Sobol",
        "club": "Club Brugge",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 4,
        "match_played": 4
    },
    {
        "serial": 64,
        "player_name": "Karavaev",
        "club": "Zenit",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 4,
        "match_played": 4
    },
    {
        "serial": 64,
        "player_name": "De Sciglio",
        "club": "Juventus",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 4,
        "match_played": 4
    },
    {
        "serial": 64,
        "player_name": "Vertonghen",
        "club": "Benfica",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 3,
        "match_played": 10
    },
    {
        "serial": 64,
        "player_name": "Azpilicueta",
        "club": "Chelsea",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 3,
        "match_played": 9
    },
    {
        "serial": 64,
        "player_name": "Martínez",
        "club": "Ajax",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 3,
        "match_played": 8
    },
    {
        "serial": 64,
        "player_name": "Origi",
        "club": "Liverpool",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 3,
        "match_played": 7
    },
    {
        "serial": 64,
        "player_name": "Mukiele",
        "club": "Leipzig",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 3,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Hefti",
        "club": "Young Boys",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 3,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Grujić",
        "club": "Porto",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 3,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Fábio Vieira",
        "club": "Porto",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 3,
        "match_played": 2
    },
    {
        "serial": 64,
        "player_name": "Gonçalo Inácio",
        "club": "Sporting CP",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 2,
        "match_played": 7
    },
    {
        "serial": 64,
        "player_name": "Pašalić",
        "club": "Atalanta",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 2,
        "match_played": 5
    },
    {
        "serial": 64,
        "player_name": "Lingard",
        "club": "Man. United",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 2,
        "match_played": 4
    },
    {
        "serial": 64,
        "player_name": "Poulsen",
        "club": "Leipzig",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 2,
        "match_played": 4
    },
    {
        "serial": 64,
        "player_name": "Schulz",
        "club": "Dortmund",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 2,
        "match_played": 4
    },
    {
        "serial": 64,
        "player_name": "Al. Miranchuk",
        "club": "Atalanta",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 2,
        "match_played": 2
    },
    {
        "serial": 64,
        "player_name": "Neuer",
        "club": "Bayern",
        "position": "Goalkeeper",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 1,
        "match_played": 9
    },
    {
        "serial": 64,
        "player_name": "Christensen",
        "club": "Chelsea",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 1,
        "match_played": 8
    },
    {
        "serial": 64,
        "player_name": "Rafa Mir",
        "club": "Sevilla",
        "position": "Forward",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 1,
        "match_played": 6
    },
    {
        "serial": 64,
        "player_name": "Kalulu",
        "club": "Milan",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 1,
        "match_played": 5
    },
    {
        "serial": 64,
        "player_name": "Danilo",
        "club": "Juventus",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 1,
        "match_played": 5
    },
    {
        "serial": 64,
        "player_name": "Tagliafico",
        "club": "Ajax",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 1,
        "match_played": 3
    },
    {
        "serial": 64,
        "player_name": "Novoa",
        "club": "Leipzig",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 1,
        "match_played": 1
    },
    {
        "serial": 64,
        "player_name": "Thiago Silva",
        "club": "Chelsea",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 0,
        "match_played": 9
    },
    {
        "serial": 64,
        "player_name": "Marquinhos",
        "club": "Paris",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 0,
        "match_played": 8
    },
    {
        "serial": 64,
        "player_name": "Klaassen",
        "club": "Ajax",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 0,
        "match_played": 7
    },
    {
        "serial": 64,
        "player_name": "Kessié",
        "club": "Milan",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 0,
        "match_played": 5
    },
    {
        "serial": 64,
        "player_name": "Gerhardt",
        "club": "Wolfsburg",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 0,
        "match_played": 5
    },
    {
        "serial": 64,
        "player_name": "Tolisso",
        "club": "Bayern",
        "position": "Midfielder",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 0,
        "match_played": 4
    },
    {
        "serial": 64,
        "player_name": "Schuurs",
        "club": "Ajax",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 0,
        "match_played": 3
    },
    {
        "serial": 64,
        "player_name": "Kryvtsov",
        "club": "Shakhtar Donetsk",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 0,
        "match_played": 3
    },
    {
        "serial": 64,
        "player_name": "Stanišić",
        "club": "Bayern",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 0,
        "match_played": 2
    },
    {
        "serial": 64,
        "player_name": "Bernardo",
        "club": "Salzburg",
        "position": "Defender",
        "assists": 1,
        "corner_taken": 0,
        "offsides": 0,
        "dribbles": 0,
        "match_played": 2
    }
]

export default players;